### ISSUE TITLE
Update RPC Spec/index.md following November releases 

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_overview_guides#61]
Re-generate the `RPC Spec/index.md` file form (https://github.com/smartdevicelink/rpc_spec/blob/master/MOBILE_API.xml) once the RPC Spec 7.0 is released in November so the `sdl_overview_guides` are up to date. 

For background see: https://github.com/smartdevicelink/sdl_overview_guides/pull/60#pullrequestreview-471857194

**Comment by jacobkeeler** [comment]
Closed via #71
