### ISSUE TITLE
Update Spelling/ Broken Links 

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_overview_guides#84]
The following items need to be fixed within the SDL Overview Guides: 

- In docs/Protocol Spec/index.md, the two broken links for `RPC Specification` should be https://github.com/smartdevicelink/sdl_core/blob/master/src/components/interfaces/HMI_API.xml. 
- In docs/Supported Platforms/index.md, `useable` should be `usable`

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_overview_guides/pull/85
